### ISSUE TITLE
Installation fails on Python 3.10.9

### ISSUE THREAD

**Issue by maheshgune** [baselsm/tvdatafeed#2]
Hi,

Trying to install TvDataFeed on Python 3.10.9.

Getting following error.

In [2]: pip install tvdatafeed
ERROR: Could not find a version that satisfies the requirement tvdatafeed (from versions: none)
ERROR: No matching distribution found for tvdatafeed
Note: you may need to restart the kernel to use updated packages.

Any clue?

Regards.

Mahesh

**Comment by maheshgune** [comment]
Installed.

**Comment by sohansoharab** [comment]
How did you fix the issue?

**Comment by Ramanoissa** [comment]
first clone it :  git clone https://github.com/rongardF/tvdatafeed.git
then use pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git
